### ISSUE TITLE
Migrate to fluent

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/i18n#18]
Fluent seems to be a much superior translation system than the current implementation via `vm`. However, our fluent plugin won't support Deno, despite the demand.

I suggest to:
1. Take the code in https://github.com/dcdunkan/grammy-fluent
2. Refactor it in a way that resembles the code style and spirit of this repo
3. Maybe bring back any missing features in case they exist
4. Release this as i18n 2.0

As a result, we would get Deno support, a better translation system, and a reactivation of this project.

@dcdunkan has offered to assist in this, but prefers not to become the maintainer of i18n.

This is a suggestion by me, who does not actually use the plugin, so take it with a grain of salt.

@EdJoPaTo @HeeroML @dcdunkan (and @roj1512 because I know you like the fork) how much time are each one of you willing to spend on this, irrespective of whether or not you'd be the main person in charge? If it's just about who is responsible, I don't mind taking that role and then in turn pinging you guys if something needs to be fixed that exceeds my knowlege of this plugin :)

**Comment by EdJoPaTo** [comment]
I will happily review PRs and so on!
I don't have that much time currently and I don't actively work on any projects using either Telegram bots or fluent currently. I only maintain my existing ones. Therefore I sadly don't have much personal interest in getting this advanced at the moment (besides wanting to see Deno for all the things :sparkles: and wanting to get this i18n / fluent mess sorted out as I dislike seeing the current state of it)

**Comment by KnorpelSenf** [comment]
@ngdangtu-vn would you want to work on this?

**Comment by ngdangtu-vn** [comment]
> @ngdangtu-vn would you want to work on this?

Thanks for the offer, and sorry for being late. Where should I start because dcdunkan already seem to work on it :D

**Comment by KnorpelSenf** [comment]
Could you review the changes in #20?

Also, we may want to think about improving the package further before doing a 2.0 release. If there's anything you'd like to see changed about the API surface of this thing, now is the perfect time to suggest it (or directly open a pull request if you like).

In the future, you could become the maintainer of the plugin if you want. While many have been interested in a good i18n plugin for Deno, no one has said they wanted to take the responsibility.

**Comment by ngdangtu-vn** [comment]
How many working hours per week requirement for me to be the maintainer?

**Comment by KnorpelSenf** [comment]
There's no such requirement.

It helps if you know the code base of the plugin, and it also helps if you're using the plugin yourself. There's no need to be an expert on any of this, but we're of course happy if you're willing to fix problems if anyone reports them (that would kinda be the point of maintaining it).

There will always be people around to help you out if you're stuck. Both here and in https://t.me/grammyjs.

**Comment by ngdangtu-vn** [comment]
Then sign me in. I will do a review on #20 later on today.
