### ISSUE TITLE
Not working on deno deploy because of `Deno.readDirSync`

### ISSUE THREAD

**Issue by waptik** [grammyjs/i18n#36]
So i tried deploying a basic bot that's using this library but because Deno Deploy supports `Deno.readDir()` instead of `Deno.readDirSync()`, the bot failed to run

![image](https://user-images.githubusercontent.com/1687551/216760976-25969d9e-d3ac-437b-847a-758603eeed03.png)

**Comment by dcdunkan** [comment]
Don't pass the `directory` option if you're running on Deno Deploy. Instead, call loadLocalesDir by youself.

```ts
const i18n = new I18n(...);
await i18n.loadLocalesDir(directory)
```
