### ISSUE TITLE
HTML link with parameters is not rendering correctly

### ISSUE THREAD

**Issue by n3nikita** [grammyjs/i18n#37]
I am encountering an issue with rendering an HTML link using 2 parameters. Only the name of the link is rendering correctly, while the link itself is not working as expected. Here is the code that I am using:

`<a href="{$link}">{$name}</a>`

When I attempt to render this link, the name of the link is displaying correctly, but the link itself is not working as expected. Instead of redirecting to the specified URL, the link is simply displaying as plain text. 

HTML link renders correctly when a static URL is used. the following code renders the link correctly:

`<a href="https://google.com/">{$name}</a>`

Any assistance in resolving this issue would be greatly appreciated. Thank you.

**Comment by dcdunkan** [comment]
Fluent, the localization system we're using has a setting "useIsolating" which defaults to true. You can read more about it and why is it on by default here: https://github.com/projectfluent/fluent.js/wiki/Unicode-Isolation.

Basically, it adds invisible characters at the start and end of placeables (variables; in your case for example, `link`). So, it becomes an invalid link and that is why its not rendered ~~correctly~~ as expected on Telegram clients. And it is also the reason why another common case `@{ $username }` isn't rendered as expected.

You can disable this setting in your i18n configuration like this:

```ts
const i18n = new I18n({
  /* ... */,
  fluentBundleOptions: {
    useIsolating: false,
  },
});
```

**Comment by n3nikita** [comment]
@dcdunkan thank you very much
