### ISSUE TITLE
Telegraf js supporting?

### ISSUE THREAD

**Issue by wolterlife** [grammyjs/i18n#41]
Is it work with telegraf js or it's all have different context?

**Comment by roziscoding** [comment]
No grammY plugin is made to be compatible with telegraf. We at most use some similar concepts to ease migration.

That being said, if you use plain JavaScript something might somehow eventually work someday, but I'd never rely on that assumption.

Anyway, I highly suggest you migrate to grammY for more mantainable code, better docs, better API, better type safety and lots of other advantages.

Check https://grammy.dev and, if you need help, ask us on https://t.me/grammyjs and we'll be glad to help 😄
