### ISSUE TITLE
cashtag entities ignored

### ISSUE THREAD

**Issue by alyavasilyeva** [grammyjs/i18n#47]
My ftl string:

```.ftl
balance =
    💰 Your balance is <b>{$balance} ${$symbol}</b>.
    ⬇️ To deposit more funds, use /deposit.
```

### Result:
![Screenshot 2024-05-15 at 13 17 22](https://github.com/grammyjs/i18n/assets/27780611/476f0960-8f5a-4597-92c7-ba6de0869d70)
All entities except for cashstrings are there.
### Expected result:
![Screenshot 2024-05-15 at 13 21 28](https://github.com/grammyjs/i18n/assets/27780611/8275ef2e-9035-4bd7-93ab-9922be33dc2f)
When passing as plain text instead of i18n localized string all works fine.

**Comment by KnorpelSenf** [comment]
Are you able to include just $ signs in the text? It might not be related to cashtags

**Comment by alyavasilyeva** [comment]
> Are you able to include just $ signs in the text? It might not be related to cashtags

Yes, apparently it's not about cashtags but about curly braces, if I copy text from the bot message and paste it in my vscode, i see some unicode characters: 
![Screenshot 2024-05-15 at 15 17 38](https://github.com/grammyjs/i18n/assets/27780611/f9a566d1-4291-4bd2-96c1-6eeb8893f87c)
If I use a plain string without variables the message is displayed as expected 🤔

**Comment by alyavasilyeva** [comment]
I just got some help in grammY telegram chat, all I had to do was adding `useIsolating: false`:
```ts
new I18n({
  fluentBundleOptions: { useIsolating: false }
});
```
I wish I could find this in the docs 😄

**Comment by KnorpelSenf** [comment]
You are right that this should perhaps be documented in our docs. It is technically more about fluent than about our plugin, but given how often bot devs run into this issue, it would still make sense to me to hint at this on https://grammy.dev/plugins/i18n.

There is an edit button at the bottom of that page. @alyavasilyeva do you feel like adding a paragraph to the docs? It can just contain a short note that this is a useful configuration. Copying over the above code snippet is probably great.

**Comment by alyavasilyeva** [comment]
Yep, I can do that!

**Comment by alyavasilyeva** [comment]
@KnorpelSenf PR ready: https://github.com/grammyjs/website/pull/1053 🙂
