### ISSUE TITLE
Add usage of `LanguageCode` type instead of `string` for `localeId`

### ISSUE THREAD

**Issue by carafelix** [grammyjs/i18n#50]
A more precise type is now found inside the grammY types than:
https://github.com/grammyjs/i18n/blob/8b86ee42dfc6a6e3685b7ce133f33639e25371f0/src/types.ts#L6

at:
https://github.com/grammyjs/types/blob/7ff098715c3fe397435c6131389677d638cdbaa3/langs.ts#L5

Making use of it should improve the ease-of-use of the plugin

**Comment by dcdunkan** [comment]
Would this be really useful?

1. First of all, an ideal usage of i18n plugin wouldn't require the code to specify the language for the user. It would be resolved through other means, where types are useless.
2. i18n can't solely depend on 2-letter language codes, as the plugin supports extended use of the locale format, like en-US, etc. Although this may not be returned from the `language_code`, the bots could have custom locale resolution where this kind of values are allowed.
3. Finally, if we will be having types for locales, shouldn't they be from the available locales? Like, if I have `en`, and `de` in my locales directory, I wouldn't want the `i18n.t()` auto-completion to show this list of locales than just "en" and "de".

These are just my concerns; I may be missing some perspective. But if you (or anyone else) believe this will be a good addition to the plugin in a valid situation, I'd be happy hear it out and add this to the plugin.

Thank you for the suggestion!

**Comment by dcdunkan** [comment]
Feel free to re-open if you find a case!

**Comment by KnorpelSenf** [comment]
Let's keep this open for a few more days in case somebody else has feedback. In general, I agree with @dcdunkan that we can close this.

**Comment by dcdunkan** [comment]
Closing now...
